### PR TITLE
Chore/change local url

### PR DESCRIPTION
**Pull request by bj0rge**

### CODE REVIEW

**Review by lili17793 — APPROVED** [review]

**Comment by lili17793** [comment]
@bj0rge I tried to use this script and if I understand well, a button or something should appear, but I don't have anything:
image

Could you show me how to use your extension?

**Comment by bj0rge** [comment]
@lili17793 
The button is actually here on your screenshot 🙃
image

When clicking on it, you'll be able to setup your different logins, and it will be prefilled for your local env.
In my env, I always use the same pattern for users: I have `bastien+accountowner@spendesk.com`, `bastien+controller@spendesk.com` and `bastien+requester@spendesk.com`
They all have the same password (not very safe, but it's local so who cares)

When setting up everything, it will always prefill the accountowner credentials, and select what is behind `+` and `@`, that way I only have to either hit "enter" to log in as AO, or just to type the alias I want then "enter" to log in

It does not do much than that, but it's time saver if you have to handle multiple roles when testing your changes

**Comment by lili17793** [comment]
@bj0rge LOVE IT! You should do a tech panel to show your tampermonkey scripts :))

**Comment by bj0rge** [comment]
> @bj0rge LOVE IT! You should do a tech panel to show your tampermonkey scripts :))

@lili17793 Haha, I'll consider that 🙃

**Pull request merged**
